apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "PORT"
              valueFrom:
                secretKeyRef:
                  key: port
                  name: {{ .Release.Name }}-secret
            - name: "HDFS_HOST"
              valueFrom:
                secretKeyRef:
                  key: hdfs_host
                  name: {{ .Release.Name }}-secret
            - name: "HDFS_PORT"
              valueFrom:
                secretKeyRef:
                  key: hdfs_port
                  name: {{ .Release.Name }}-secret
            - name: "KRB_HOST"
              valueFrom:
                secretKeyRef:
                  key: krb_host
                  name:  {{ .Release.Name }}-secret
            - name: "KRB_USERNAME"
              valueFrom:
                secretKeyRef:
                  key: krb_username
                  name:  {{ .Release.Name }}-secret
            - name: "KRB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: krb_password
                  name:  {{ .Release.Name }}-secret
            - name: "KRB_REALM"
              valueFrom:
                secretKeyRef:
                  key: krb_realm
                  name:  {{ .Release.Name }}-secret
            - name: "KRB_USER_PRINCIPAL"
              valueFrom:
                secretKeyRef:
                  key: krb_user_principal
                  name:  {{ .Release.Name }}-secret
            - name: "KRB_HNN_PRINCIPAL"
              valueFrom:
                secretKeyRef:
                  key: krb_hnn_principal
                  name:  {{ .Release.Name }}-secret
          ports:
            - name: external
              containerPort: 8080
              protocol: TCP
            - name: internal
              containerPort: 8585
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: internal
          readinessProbe:
            httpGet:
              path: /health
              port: internal
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
