apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  port: {{ printf "%d" .Values.port | b64enc }}
  hdfs_host: {{ .Values.hdfs_host | b64enc }}
  hdfs_port: {{ printf "%d" .Values.hdfs_port | b64enc }}
  krb_host: {{ .Values.krb_host | b64enc }}
  krb_username: {{ .Values.krb_username | b64enc }}
  krb_password: {{ .Values.krb_password | b64enc }}
  krb_realm: {{ .Values.krb_realm | b64enc }}
  krb_user_principal: {{ .Values.krb_user_principal | b64enc }}
  krb_hnn_principal: {{ .Values.krb_hnn_principal | b64enc }}
