apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  port: {{ printf "%d" .Values.port | b64enc }}
  hdfs_host: {{ .Values.hdfs_host | b64enc }}
  hdfs_port: {{ printf "%d" .Values.hdfs_port | b64enc }}
  tvs_address: {{ .Values.tvs_address | b64enc }}
  tvs_client_id: {{ .Values.tvs_client_id | b64enc }}
  tvs_client_secret: {{ .Values.tvs_client_secret | b64enc }}
